name: CI

on:
  push:
    branches: ["main", "dev"]
  pull_request:
    branches: ["main", "dev"]

  workflow_dispatch:

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v6.6.1

      - name: Ruff format
        run: uv run ruff format --check

      - name: Ruff
        run: uv run ruff check

      - name: WPS
        run: uv run flake8 orapack tests --select WPS

      - name: Pyrefly
        run: uv run pyrefly check

      - name: Pytest
        run: uv run pytest
